name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linter (ESLint)
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run formatter (Prettier)
      - name: Run Prettier
        run: npx prettier --write ./src/

      # Step 6: Run tests (Jest)
      - name: Run tests
        run: CI=true npm run test

      # Step 7: Build the project
      - name: Build the project
        run: npm run build
      
        

     
     
     
        
    
      
